events {}

http {
    upstream rate_limiter_backend {
        server app1:8081;
        server app2:8081;
        server app3:8081;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://rate_limiter_backend;
        }
    }
}
